version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: swapp_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${ DB_NAME }
      MYSQL_ROOT_PASSWORD: ${ DB_PASSWORD }

    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql-script:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin
    container_name: swapp_pma
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"

volumes:
  db_data: