version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: swapp_mysql
    restart: always
    environment:
      MYSQL_DATABASE: swapp_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql-script:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: swapp_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data: